#!/bin/bash -e

echo "% of Total Merges               Author  # of Merges  % of Commits"
mergeCounts=`git log --first-parent --merges --pretty='format:%an' | sort | uniq -c | sort -nr`
totalMerges=`git log --first-parent --merges --oneline | wc -l`

while read -r line; do
   authorMerges=`awk '{print $1}' <<< "$line"`
   author=`sed "s/$authorMerges //" <<< "$line"`
   authorCommits=`git log --first-parent --oneline --author="$author" | wc -l`
   totalPercentage=`echo "scale=2; (100*$authorMerges) / $totalMerges" | bc`
   authorPercentage=`echo "scale=2; (100*$authorMerges) / $authorCommits" | bc`
   printf "%17.2f %20s %12i %13.2f\n" "$totalPercentage" "$author" "$authorMerges" "$authorPercentage"
done <<< "$mergeCounts"

